module.exports = {
  preset: 'jest-expo',
  testEnvironment: 'node',
  automock: false,
  resetMocks: false,
  setupFiles: [
    '<rootDir>/tests/setup.jest.ts',
    './node_modules/react-native-gesture-handler/jestSetup.js',
  ],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
  transformIgnorePatterns: [
    'node_modules/(?!(?:.pnpm/)?((jest-)?react-native|@react-native(-community)?|expo(nent)?|@expo(nent)?/.*|@expo-google-fonts/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|react-native-svg))',
  ],

  testPathIgnorePatterns: [
    '/node_modules/',
    '/scripts/',
    '/.eslintrc.js',
    '/.prettierrc.js',
    '/.svgrrc.js',
    '/app.config.js',
    '/jest.config.js',
    '/metro.config.js',
    '/src/components/.*?/index\\.ts$',
    '/src/feat/auth/types/.*?/index\\.ts$',
    '/src/hooks/index\\.ts$',
    '/src/theme/index\\.ts$',
    '/src/constants/index\\.ts$',
    '/src/services/index\\.ts$',
    '/src/theme/spacings\\.ts$',
    '/src/theme/radius\\.ts$',
    '/src/utils/index\\.ts$',
    '/src/stores/index\\.ts$',
    '/src/translations/locales/index\\.ts$',
    '/e2e/',
  ],
  coveragePathIgnorePatterns: [
    '/node_modules/',
    '/scripts/',
    '/.eslintrc.js',
    '/.prettierrc.js',
    '/.svgrrc.js',
    '/app.config.js',
    '/jest.config.js',
    '/metro.config.js',
    '/src/components/.*?/index\\.ts$',
    '/src/hooks/index\\.ts$',
    '/src/theme/index\\.ts$',
    '/src/theme/spacings\\.ts$',
    '/src/constants/index\\.ts$',
    '/src/services/index\\.ts$',
    '/src/utils/index\\.ts$',
    '/src/theme/radius\\.ts$',
    '/src/stores/index\\.ts$',
    '/src/translations/locales/index\\.ts$',
  ],
  collectCoverage: true,
  // collectCoverageFrom: [
  //   '**/*.{ts,tsx}',
  //   '!**/coverage/**',
  //   '!**/node_modules/**',
  //   '!**/babel.config.js',
  // ],
};
